### ISSUE TITLE
collaboration with MsgPack2

### ISSUE THREAD

**Issue by jrevels** [JuliaIO/MsgPack.jl#29]
Hello!

I've been working on https://github.com/beacon-biosignals/MsgPack2.jl, which is basically MsgPack.jl re-implemented with [JSON3](https://github.com/quinnj/JSON3.jl)-like features. I'm still writing tests, need to add a manual to the README, etc., but was wondering if there'd be any interest in simply replacing this package's implementation with the new one (getting rid of the separate MsgPack2 repo altogether)?

The main benefit would be to avoid duplicating maintainer efforts and avoid the slightly confusing situation for users that's arose with e.g. having multiple JSON packages. However, it is a drastically different implementation compared to the current one (it'd definitely require a major version bump), so I'd understand if folding it into here would be undesirable 🙂

If the maintainer here (@kmsquire, it seems?) is amenable to this idea and gives me access to this repo, I can open up a PR to fold MsgPack2 into here in a week or so (I still need to finish docs + tests + https://github.com/beacon-biosignals/MsgPack2.jl/issues/8) and take on a maintainer role. Let me know what you think!

**Comment by jrevels** [comment]
Thanks!

> Assuming nothing breaks, I have no problem at all if you simply replace the existing implementation.

MsgPack2 doesn't yet implement any of the MessagePack Extension stuff, so that would break (ref https://github.com/beacon-biosignals/MsgPack2.jl/issues/8). We could hold off until that's implemented if that's a concern.

**Comment by kmsquire** [comment]
Yeah, it would probably be good to implement extension types. I'm not sure how much they're used, but they are part of the official spec, and it would be better not to break existing code by removing them.

**Comment by jrevels** [comment]
Sounds good! I'll see if I can bang out an implementation for extension types this weekend/next week, then I'll open a PR here.

**Comment by jrevels** [comment]
closed by #30
