### ISSUE TITLE
Move to JuliaIO organization

### ISSUE THREAD

**Issue by kmsquire** [JuliaIO/MsgPack.jl#9]
Cc: @IainNZ, @WestleyArgentum

Julia Web seems like a more appropriate place for this.  Iain and Westley seem to be the only members, currently--would you be okay with that?

Assuming so, it would be good if @sbillig, @binarybana, and myself still had commit access to the repo, if not the organization.

(As an aside, have you considered inviting others to the organization?  If they're interested, @astrieanna, @zachallaun, and @danielmendel come to mind--I believe they were the originators of the webstack.)

**Comment by IainNZ** [comment]
I'm not sure I follow the connection to JuliaWeb - ins't this something like ProtocolBuffers?

(I'm not particularly invested in or interested in JuliaWeb, it just hurt to see so many packages in a failing state so I've been trying to keep them ticking over and merging PRs since their original authors have moved on.)

**Comment by kmsquire** [comment]
Yes, I believe it fills the same role as ProtocolBuffers (and JSON).  

I guess it depends on how broadly or narrowly you define "Web".  As I understand it (from a mostly outside perspective), these are all serialization methods which are used in or for web applications more frequently than other kinds of applications.  So someone doing web development would probably be looking for them (and other things) in the same place as the actual web stack.

That may be too broad a definition, though, because it probably captures a few other packages (ZMQ.jl, ProtoBuf.jl, JSON.jl, HiRedis.jl, etc.),  that aren't under JuliaWeb right now either.

More than anything, I took over this package because I needed it briefly, and am no longer using it, so I was looking for a more appropriate place.  (At the least, @binarybana has been helping take care of it.)

(I kind of figured that about your involvement with JuliaWeb.  I do want to offer appreciation for all of the work you have been doing to keep Julia packages in good shape--thanks!!)

I forget, have you put out a call on the mailing list for users interested in helping with Julia Web?  If not, we might do so, and see if anyone has an opinion about including things like this.  Of course, given our target audience and the number of people actually using these, I'm not sure we'd be overwhelmed with responses...

**Comment by WestleyArgentum** [comment]
It's not a super strong opinion, but I think this does fit better with JSON.jl, ZMQ.jl, etc. Maybe it should go under JuliaLang?

Also @IainNZ it really is awesome seeing those packages stay up to date!

**Comment by kmsquire** [comment]
@WestleyArgentum, given where those other packages are right now, I guess that kind of makes sense. 

What would you think of the idea of moving most or all of those under JuliaWeb, under the same reasoning I used above, i.e., that they're not web technologies per se, but that they're most commonly used there?  I'd love to hear thoughts which support or refute this idea.

**Comment by WestleyArgentum** [comment]
I think in a perfect world they would all fall into a nicely named organization of their own, however, in a more realistic one pulling them into JuliaWeb might be a good way to kickstart activity there :)

Given that, I would support the idea. As long as no one else in @JuliaWeb objects, we can transfer this in. Then maybe we can propose transferring similar packages to JuliaLang at large.

**Comment by kmsquire** [comment]
When I looked, the only public members of JuliaWeb were you and @IainNZ. Are there others?

It might be nice to get JSON.jl, MsgPack.jl, and ProtoBuf.jl to have similar interfaces, and having them in the same organization would be a nice push in that direction.

**Comment by IainNZ** [comment]
I see 10 people, maybe those other people have not accepted publishing membership?

I'm not sure that JSON.jl will move, its a pretty critical package and when it breaks it really resonates widely in the package ecosystem - having it in JuliaLang seems to help with rapid response/many eyes.

**Comment by WestleyArgentum** [comment]
You're probably right about JSON.jl... would `JuliaIO` be a good group name for this and similar packages?

**Comment by WestleyArgentum** [comment]
Although @kmsquire, if you really just want to transfer MsgPack.jl, it doesn't seem like there are any strong objections and I think I have the permissions required in JuliaWeb

**Comment by tkelman** [comment]
Looks like this was done some time in the last few weeks. Make sure AppVeyor and Travis are re-enabled.

**Comment by iamed2** [comment]
Badge links still point to the old repo and AppVeyor and Coveralls don't appear to be enabled

**Comment by kmsquire** [comment]
@iamed2, badges now fixed.  Thanks!

**Comment by iamed2** [comment]
Clicking the Appveyor badge still gives me "Project not found or access denied"

**Comment by kmsquire** [comment]
I forgot that AppVeyor still needed to be on my personal account.  Should be fixed in #22.  Will merge once CI finishes.
